version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - /home/scottserven/docker-configs/team/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "@PASSword123"
    ports:
      - "3306:3306"

  php:
    image: team-twitch-chat-history
    depends_on:
      - db
    ports:
      - "8000:80"



